-- MySQL Script generated by MySQL Workbench
-- 08/16/17 10:57:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gushiyou_app
-- -----------------------------------------------------
-- 故事友APP数据库

-- -----------------------------------------------------
-- Schema gushiyou_app
--
-- 故事友APP数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gushiyou_app` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `gushiyou_app` ;

-- -----------------------------------------------------
-- Table `gushiyou_app`.`user_ext`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`user_ext` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '扩展ID',
  `realName` VARCHAR(32) NULL DEFAULT '' COMMENT '姓名',
  `address` VARCHAR(100) NULL DEFAULT '' COMMENT '住址',
  `idCard` VARCHAR(30) NULL DEFAULT '' COMMENT '身份证号',
  `qq` VARCHAR(12) NULL DEFAULT '' COMMENT 'QQ号',
  `wechat` VARCHAR(21) NULL DEFAULT '' COMMENT '微信号',
  `weibo` VARCHAR(31) NULL DEFAULT '' COMMENT '微博',
  `searchMeByGuShiHao` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否可通过故事号搜索到我',
  `enableFriendWord` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否开启好友口令',
  `friendWord` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '好友口令',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '用户扩展表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `gushihao` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '故事号',
  `simpleGushihao` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '简化故事号',
  `password` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '密码',
  `salt` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '盐',
  `protectPwd` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '密保口令',
  `appDBPwd` VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'app数据库密码',
  `pseudonym` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '笔名',
  `simplePseudonym` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '简化笔名',
  `avatar` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '头像',
  `cover` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '主页封面',
  `signature` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '简介',
  `gender` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '性别(0：女，1： 男)',
  `birthdate` DATE NULL COMMENT '生日',
  `hometown` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '家乡',
  `mobile` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手机号',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `certification` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '认证状态(0:未认证，1:个人认证，2:机构认证)',
  `imaccid` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '即时通讯系统用户ID',
  `imtoken` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '即时通讯系统用户密码',
  `extId` BIGINT(20) UNSIGNED NOT NULL COMMENT '扩展ID',
  `findPwdUnbanTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '找回密码解禁时间',
  `unbanTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '解封时间',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '帐号状态（0：注销，1：正常）',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_ext1_idx` (`extId` ASC),
  INDEX `simplePseudonym_index` (`simplePseudonym` ASC),
  INDEX `simpleGushihao_index` (`simpleGushihao` ASC),
  INDEX `mobile_index` (`mobile` ASC),
  INDEX `email_index` (`email` ASC),
  INDEX `simpleGushihao_simplePseudonym_index` (`simpleGushihao` ASC, `simplePseudonym` ASC),
  CONSTRAINT `fk_user_user_ext1`
    FOREIGN KEY (`extId`)
    REFERENCES `gushiyou_app`.`user_ext` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`right`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`right` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权利ID',
  `rightName` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '权利名',
  `description` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '描述',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `privilegeName_UNIQUE` (`rightName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '权利表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`friend_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`friend_relation` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '好友关系ID',
  `userId` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
  `friendId` BIGINT(20) UNSIGNED NOT NULL COMMENT '好友ID',
  `remark` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '备注',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否为好友',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `fk_friend_relation_user2_idx` (`friendId` ASC),
  INDEX `fk_friend_relation_user1_idx` (`userId` ASC),
  INDEX `userId_friendId` (`userId` ASC, `friendId` ASC),
  CONSTRAINT `fk_friend_relation_user2`
    FOREIGN KEY (`friendId`)
    REFERENCES `gushiyou_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_relation_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `gushiyou_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '好友关系表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`follow_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`follow_relation` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关注关系ID',
  `userId` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
  `followingId` BIGINT(20) UNSIGNED NOT NULL COMMENT '被关注者ID',
  `remark` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '备注',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `fk_follow_relation_user1_idx` (`followingId` ASC),
  INDEX `fk_follow_relation_user2_idx` (`userId` ASC),
  INDEX `userId_followingId` (`userId` ASC, `followingId` ASC),
  CONSTRAINT `fk_follow_relation_user1`
    FOREIGN KEY (`followingId`)
    REFERENCES `gushiyou_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_follow_relation_user2`
    FOREIGN KEY (`userId`)
    REFERENCES `gushiyou_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '关注关系表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`blacklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`blacklist` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '黑名单ID',
  `userId` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
  `blackId` BIGINT(20) UNSIGNED NOT NULL COMMENT '被拉黑者ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `fk_blacklist_user1_idx` (`userId` ASC),
  INDEX `fk_blacklist_user2_idx` (`blackId` ASC),
  CONSTRAINT `fk_blacklist_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `gushiyou_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blacklist_user2`
    FOREIGN KEY (`blackId`)
    REFERENCES `gushiyou_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '黑名单表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`right_expires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`right_expires` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权利有效期ID',
  `userId` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
  `rightId` BIGINT(20) UNSIGNED NOT NULL COMMENT '权利ID',
  `expires` DATETIME NULL COMMENT '到期时间',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `fk_right_expires_user1_idx` (`userId` ASC),
  INDEX `fk_right_expires_right1_idx` (`rightId` ASC),
  CONSTRAINT `fk_right_expires_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `gushiyou_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_right_expires_right1`
    FOREIGN KEY (`rightId`)
    REFERENCES `gushiyou_app`.`right` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '权利有效期表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`config` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '配置ID',
  `module` VARCHAR(32) NOT NULL COMMENT '模块名',
  `item` VARCHAR(64) NOT NULL COMMENT '配置项',
  `value` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '配置值',
  `description` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '描述',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '配置表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`secret_key`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`secret_key` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '密钥ID',
  `keyName` VARCHAR(64) NOT NULL COMMENT '密钥名',
  `keyValue` VARCHAR(1024) NOT NULL COMMENT '密钥值',
  `comment` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '备注',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `item_UNIQUE` (`keyName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '密钥表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`terminal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`terminal` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '终端ID',
  `userId` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
  `platform` VARCHAR(32) NULL DEFAULT '' COMMENT '平台(app,web,pc)',
  `app` VARCHAR(45) NULL DEFAULT '' COMMENT '应用端',
  `appChannel` VARCHAR(32) NULL DEFAULT '' COMMENT '应用端来源渠道',
  `deviceId` VARCHAR(64) NULL DEFAULT '' COMMENT '设备ID',
  `deviceModel` VARCHAR(64) NULL DEFAULT '' COMMENT '设备型号',
  `resolution` VARCHAR(32) NULL DEFAULT '' COMMENT '分辨率',
  `network` VARCHAR(32) NULL DEFAULT '' COMMENT '联网方式',
  `networkOperator` VARCHAR(32) NULL DEFAULT '' COMMENT '网络运营商',
  `os` VARCHAR(32) NULL DEFAULT '' COMMENT '操作系统',
  `locale` VARCHAR(32) NULL DEFAULT '' COMMENT '语言环境',
  `lng` VARCHAR(32) NULL DEFAULT '' COMMENT '经度',
  `lat` VARCHAR(32) NULL DEFAULT '' COMMENT '纬度',
  `location` VARCHAR(64) NULL DEFAULT '' COMMENT '位置',
  `loginIp` VARCHAR(64) NULL DEFAULT '0.0.0.0' COMMENT '登录IP地址',
  `loginTime` DATETIME NULL COMMENT '登录时间',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `fk_ terminal_user1_idx` (`userId` ASC),
  CONSTRAINT `fk_ terminal_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `gushiyou_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '终端表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`hometown`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`hometown` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '家乡ID',
  `name` VARCHAR(20) NOT NULL COMMENT '家乡名',
  `level` TINYINT(3) NOT NULL COMMENT '级别',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '家乡表';


-- -----------------------------------------------------
-- Table `gushiyou_app`.`right_unban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_app`.`right_unban` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权利有效期ID',
  `userId` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
  `rightId` BIGINT(20) UNSIGNED NOT NULL COMMENT '权利ID',
  `unbanTime` DATETIME NULL COMMENT '解封时间',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `fk_right_expires_user1_idx` (`userId` ASC),
  INDEX `fk_right_expires_right1_idx` (`rightId` ASC),
  CONSTRAINT `fk_right_expires_user10`
    FOREIGN KEY (`userId`)
    REFERENCES `gushiyou_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_right_expires_right10`
    FOREIGN KEY (`rightId`)
    REFERENCES `gushiyou_app`.`right` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '权利解封表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
