-- MySQL Script generated by MySQL Workbench
-- 12/30/16 16:27:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gushiyou_admin
-- -----------------------------------------------------
-- 故事友后台管理数据库

-- -----------------------------------------------------
-- Schema gushiyou_admin
--
-- 故事友后台管理数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gushiyou_admin` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `gushiyou_admin` ;

-- -----------------------------------------------------
-- Table `gushiyou_admin`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_admin`.`role` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `roleName` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '角色名',
  `description` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '描述',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roleName_UNIQUE` (`roleName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `gushiyou_admin`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_admin`.`user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `userName` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户名',
  `realName` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '姓名',
  `gender` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '性别(0：女，1： 男)',
  `birthdate` DATE NULL COMMENT '出生日期',
  `address` VARCHAR(100) NULL DEFAULT '' COMMENT '住址',
  `password` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '密码',
  `salt` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '盐',
  `avatar` VARCHAR(256) NULL DEFAULT '' COMMENT '头像',
  `email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `mobile` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '手机号',
  `idCard` VARCHAR(30) NULL DEFAULT '' COMMENT '身份证号',
  `telephone` VARCHAR(20) NULL DEFAULT '' COMMENT '电话',
  `qq` VARCHAR(12) NULL DEFAULT '' COMMENT 'QQ号',
  `wechat` VARCHAR(21) NULL DEFAULT '' COMMENT '微信号',
  `weibo` VARCHAR(31) NULL DEFAULT '' COMMENT '微博',
  `occupation` VARCHAR(45) NULL DEFAULT '' COMMENT '职业',
  `loginIP` VARCHAR(45) NOT NULL DEFAULT '0.0.0.0' COMMENT '登录IP地址',
  `loginDevID` VARCHAR(64) NULL DEFAULT '' COMMENT '登录设备ID',
  `loginTime` DATETIME NULL COMMENT '登录时间',
  `lastLoginTime` DATETIME NULL COMMENT '上次登录时间',
  `roleId` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色ID',
  `creatorId` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建者ID',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '帐号状态（0：删除，1：正常）',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_idx` (`roleId` ASC),
  INDEX `fk_user_user1_idx` (`creatorId` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`roleId`)
    REFERENCES `gushiyou_admin`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user1`
    FOREIGN KEY (`creatorId`)
    REFERENCES `gushiyou_admin`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `gushiyou_admin`.`privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_admin`.`privilege` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权限ID',
  `privilegeName` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '权限名',
  `description` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '描述',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `privilegeName_UNIQUE` (`privilegeName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '权限表';


-- -----------------------------------------------------
-- Table `gushiyou_admin`.`role_has_privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_admin`.`role_has_privilege` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色权限ID',
  `roleId` BIGINT(20) UNSIGNED NOT NULL COMMENT '角色ID',
  `privilegeId` BIGINT(20) UNSIGNED NOT NULL COMMENT '权限ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `fk_role_has_privilege_privilege1_idx` (`privilegeId` ASC),
  INDEX `fk_role_has_privilege_role1_idx` (`roleId` ASC),
  CONSTRAINT `fk_role_has_privilege_role1`
    FOREIGN KEY (`roleId`)
    REFERENCES `gushiyou_admin`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_role_has_privilege_privilege1`
    FOREIGN KEY (`privilegeId`)
    REFERENCES `gushiyou_admin`.`privilege` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '角色权限中间表';


-- -----------------------------------------------------
-- Table `gushiyou_admin`.`operation_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_admin`.`operation_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '操作日志ID',
  `operatorId` BIGINT(20) UNSIGNED NOT NULL COMMENT '操作者ID',
  `action` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '操作',
  `path` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '路径',
  `params` VARCHAR(1024) NULL DEFAULT '' COMMENT '参数',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `fk_operation_log_user1_idx` (`operatorId` ASC),
  CONSTRAINT `fk_operation_log_user1`
    FOREIGN KEY (`operatorId`)
    REFERENCES `gushiyou_admin`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '操作日志表';


-- -----------------------------------------------------
-- Table `gushiyou_admin`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_admin`.`menu` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '菜单ID',
  `menuName` VARCHAR(45) NOT NULL COMMENT '菜单名',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `menuName_UNIQUE` (`menuName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '菜单表';


-- -----------------------------------------------------
-- Table `gushiyou_admin`.`menu_has_privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gushiyou_admin`.`menu_has_privilege` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '菜单权限ID',
  `menuId` BIGINT(20) UNSIGNED NOT NULL COMMENT '菜单ID',
  `privilegeId` BIGINT(20) UNSIGNED NOT NULL COMMENT '权限ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `fk_menu_has_privilege1_privilege1_idx` (`privilegeId` ASC),
  INDEX `fk_menu_has_privilege1_menu1_idx` (`menuId` ASC),
  CONSTRAINT `fk_menu_has_privilege1_menu1`
    FOREIGN KEY (`menuId`)
    REFERENCES `gushiyou_admin`.`menu` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_menu_has_privilege1_privilege1`
    FOREIGN KEY (`privilegeId`)
    REFERENCES `gushiyou_admin`.`privilege` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10000
COMMENT = '菜单权限中间表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
